<?php
/**
 * GetAlliancesAllianceIdIconsOkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Swagger\Client\Eve;

/**
 * GetAlliancesAllianceIdIconsOkTest Class Doc Comment
 *
 * @category    Class
 * @description 200 ok object
 * @package     Swagger\Client\Eve
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetAlliancesAllianceIdIconsOkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetAlliancesAllianceIdIconsOk"
     */
    public function testGetAlliancesAllianceIdIconsOk()
    {
    }

    /**
     * Test attribute "px64x64"
     */
    public function testPropertyPx64x64()
    {
    }

    /**
     * Test attribute "px128x128"
     */
    public function testPropertyPx128x128()
    {
    }
}
