<?php
/**
 * GetCorporationsCorporationIdWalletsDivisionJournal200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client\Eve;

/**
 * GetCorporationsCorporationIdWalletsDivisionJournal200OkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     Swagger\Client\Eve
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCorporationsCorporationIdWalletsDivisionJournal200OkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetCorporationsCorporationIdWalletsDivisionJournal200Ok"
     */
    public function testGetCorporationsCorporationIdWalletsDivisionJournal200Ok()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {
    }

    /**
     * Test attribute "ref_type"
     */
    public function testPropertyRefType()
    {
    }

    /**
     * Test attribute "first_party_id"
     */
    public function testPropertyFirstPartyId()
    {
    }

    /**
     * Test attribute "first_party_type"
     */
    public function testPropertyFirstPartyType()
    {
    }

    /**
     * Test attribute "second_party_id"
     */
    public function testPropertySecondPartyId()
    {
    }

    /**
     * Test attribute "second_party_type"
     */
    public function testPropertySecondPartyType()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "tax_receiver_id"
     */
    public function testPropertyTaxReceiverId()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "extra_info"
     */
    public function testPropertyExtraInfo()
    {
    }
}
