<?php
/**
 * GetCorporationsCorporationIdContainersLogs200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Swagger\Client\Eve;

use PHPUnit\Framework\TestCase;

/**
 * GetCorporationsCorporationIdContainersLogs200OkTest Class Doc Comment
 *
 * @category    Class
 * @description 200 ok object
 * @package     Swagger\Client\Eve
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetCorporationsCorporationIdContainersLogs200OkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetCorporationsCorporationIdContainersLogs200Ok"
     */
    public function testGetCorporationsCorporationIdContainersLogs200Ok()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }

    /**
     * Test attribute "character_id"
     */
    public function testPropertyCharacterId()
    {
    }

    /**
     * Test attribute "container_id"
     */
    public function testPropertyContainerId()
    {
    }

    /**
     * Test attribute "container_type_id"
     */
    public function testPropertyContainerTypeId()
    {
    }

    /**
     * Test attribute "location_flag"
     */
    public function testPropertyLocationFlag()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "logged_at"
     */
    public function testPropertyLoggedAt()
    {
    }

    /**
     * Test attribute "new_config_bitmask"
     */
    public function testPropertyNewConfigBitmask()
    {
    }

    /**
     * Test attribute "old_config_bitmask"
     */
    public function testPropertyOldConfigBitmask()
    {
    }

    /**
     * Test attribute "password_type"
     */
    public function testPropertyPasswordType()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
    }
}
