<?php
/**
 * GetCharactersCharacterIdAssetsNotFoundTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.12
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Swagger\Client\Eve\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetCharactersCharacterIdAssetsNotFoundTest Class Doc Comment
 *
 * @category    Class
 * @description Requested page does not exist
 * @package     Swagger\Client\Eve
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetCharactersCharacterIdAssetsNotFoundTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetCharactersCharacterIdAssetsNotFound"
     */
    public function testGetCharactersCharacterIdAssetsNotFound()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
