<?php
/**
 * GetKillmailsKillmailIdKillmailHashPositionTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Swagger\Client\Eve\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetKillmailsKillmailIdKillmailHashPositionTest Class Doc Comment
 *
 * @category    Class
 * @description Coordinates of the victim in Cartesian space relative to the Sun
 * @package     Swagger\Client\Eve
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetKillmailsKillmailIdKillmailHashPositionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetKillmailsKillmailIdKillmailHashPosition"
     */
    public function testGetKillmailsKillmailIdKillmailHashPosition()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "z"
     */
    public function testPropertyZ()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
