<?php
/**
 * BookmarksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Eve;

use \Swagger\Client\Eve\Configuration;
use \Swagger\Client\Eve\ApiException;
use \Swagger\Client\Eve\ObjectSerializer;

/**
 * BookmarksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BookmarksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCharactersCharacterIdBookmarks
     *
     * List bookmarks.
     *
     */
    public function testGetCharactersCharacterIdBookmarks()
    {
    }

    /**
     * Test case for getCharactersCharacterIdBookmarksFolders
     *
     * List bookmark folders.
     *
     */
    public function testGetCharactersCharacterIdBookmarksFolders()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdBookmarks
     *
     * List corporation bookmarks.
     *
     */
    public function testGetCorporationsCorporationIdBookmarks()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdBookmarksFolders
     *
     * List corporation bookmark folders.
     *
     */
    public function testGetCorporationsCorporationIdBookmarksFolders()
    {
    }
}
