<?php
/**
 * WalletApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Eve;

use \Swagger\Client\Eve\Configuration;
use \Swagger\Client\Eve\ApiException;
use \Swagger\Client\Eve\ObjectSerializer;

/**
 * WalletApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client\Eve
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WalletApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCharactersCharacterIdWallet
     *
     * Get a character's wallet balance.
     *
     */
    public function testGetCharactersCharacterIdWallet()
    {
    }

    /**
     * Test case for getCharactersCharacterIdWalletJournal
     *
     * Get character wallet journal.
     *
     */
    public function testGetCharactersCharacterIdWalletJournal()
    {
    }

    /**
     * Test case for getCharactersCharacterIdWalletTransactions
     *
     * Get wallet transactions.
     *
     */
    public function testGetCharactersCharacterIdWalletTransactions()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdWallets
     *
     * Returns a corporation's wallet balance.
     *
     */
    public function testGetCorporationsCorporationIdWallets()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdWalletsDivisionJournal
     *
     * Get corporation wallet journal.
     *
     */
    public function testGetCorporationsCorporationIdWalletsDivisionJournal()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdWalletsDivisionTransactions
     *
     * Get corporation wallet transactions.
     *
     */
    public function testGetCorporationsCorporationIdWalletsDivisionTransactions()
    {
    }
}
